// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex h-screen\"><!-- Sidebar placeholder --><aside id=\"sidebar\" class=\"w-64 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 p-4\"><h1 class=\"text-xl font-bold text-indigo-600 dark:text-indigo-400\">ReviewHub</h1><p class=\"text-sm text-gray-500 dark:text-gray-400 mt-2\">PR Dashboard</p><div id=\"pr-list\" class=\"mt-4\"><p class=\"text-gray-400 dark:text-gray-500 text-sm\">PR feed loading in Plan 02...</p></div></aside><!-- Main content area --><main class=\"flex-1 p-6 overflow-y-auto\"><div id=\"pr-detail\" class=\"flex items-center justify-center h-full\"><p class=\"text-gray-400 dark:text-gray-500 text-lg\">Select a PR to view details</p></div></main></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
