# MD013 - Line length (disabled - many doc lines exceed 80 chars)
MD013: false

# MD033 - Inline HTML (allow sub tags used in planning docs)
MD033:
  allowed_elements:
    - sub
    - sup
    - details
    - summary

# MD041 - First line should be a top-level heading (disabled for planning files)
MD041: false

# MD024 - Multiple headings with the same content (allow in planning docs)
MD024: false
