CREATE TABLE IF NOT EXISTS ignored_prs (
    pr_id      INTEGER NOT NULL PRIMARY KEY,
    ignored_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pr_id) REFERENCES pull_requests(id) ON DELETE CASCADE
);
