// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/ericfisherdev/mygitpanel/internal/adapter/driving/web/viewmodel"
)

// PRReviewsSection renders the complete reviews section for a PR detail panel.
// It includes all review threads, issue comments, and the review submit form.
// This component is the morph swap target for reply and review submit responses.
// The outer div carries id="pr-reviews-section" so HTMX can find it.
func PRReviewsSection(pr viewmodel.PRDetailViewModel, owner, repo string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"pr-reviews-section\" class=\"space-y-6\"><!-- Review threads --><section><h3 class=\"text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3\">Review Threads ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if pr.UnresolvedThreads > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"ml-2 text-xs font-normal text-yellow-600 dark:text-yellow-400\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(pr.UnresolvedThreads))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapter/driving/web/templates/components/pr_reviews_section.templ`, Line: 19, Col: 115}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " unresolved</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if pr.ResolvedThreads > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span class=\"ml-2 text-xs font-normal text-green-600 dark:text-green-400\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(pr.ResolvedThreads))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapter/driving/web/templates/components/pr_reviews_section.templ`, Line: 22, Col: 111}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " resolved</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(pr.Threads) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<p class=\"text-sm text-gray-400 dark:text-gray-500 py-2\">No review threads</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		for _, thread := range pr.Threads {
			templ_7745c5c3_Err = ReviewThread(thread, owner, repo, pr.Number).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</section><!-- Issue comments -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(pr.IssueComments) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<section><h3 class=\"text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3\">General Comments</h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, comment := range pr.IssueComments {
				templ_7745c5c3_Err = IssueCommentCard(comment).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<!-- Review submit form --><section><h3 class=\"text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3\">Submit Review</h3><div x-data=\"{ pendingComments: [], reviewBody: '', reviewEvent: 'COMMENT' }\" x-init=\"$refs.commentsInput.value = JSON.stringify(pendingComments); $watch('pendingComments', value => { $refs.commentsInput.value = JSON.stringify(value) })\" class=\"bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4 space-y-4\"><!-- Pending line comments list --><div x-show=\"pendingComments.length > 0\"><p class=\"text-xs font-medium text-gray-600 dark:text-gray-400 mb-2\">Pending line comments (<span x-text=\"pendingComments.length\"></span>):</p><ul class=\"space-y-1\"><template x-for=\"(comment, index) in pendingComments\" :key=\"index\"><li class=\"flex items-start gap-2 text-xs text-gray-700 dark:text-gray-300\"><span class=\"font-mono text-gray-500\" x-text=\"comment.path + ':' + comment.line\"></span> <span class=\"flex-1 truncate\" x-text=\"comment.body\"></span> <button type=\"button\" @click=\"pendingComments.splice(index, 1)\" class=\"text-red-500 hover:text-red-700 shrink-0\" aria-label=\"Remove pending comment\">&#10005;</button></li></template></ul></div><!-- Review form --><form hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/app/prs/%s/%s/%d/review", owner, repo, pr.Number))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapter/driving/web/templates/components/pr_reviews_section.templ`, Line: 69, Col: 78}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" hx-target=\"#pr-reviews-section\" hx-swap=\"morph\" @htmx:after-request.camel=\"if(event.detail.successful){ pendingComments = []; reviewBody = ''; reviewEvent = 'COMMENT' }\" hx-on:htmx:response-error=\"document.getElementById('pr-review-error').textContent = event.detail.xhr.responseText || 'Submission failed. Please try again.'\" class=\"space-y-3\"><input type=\"hidden\" name=\"commit_sha\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(pr.HeadSHA)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapter/driving/web/templates/components/pr_reviews_section.templ`, Line: 76, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\"> <input type=\"hidden\" name=\"comments\" x-ref=\"commentsInput\"><div><label class=\"block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1\" for=\"review-event\">Review type</label> <select id=\"review-event\" name=\"event\" x-model=\"reviewEvent\" class=\"w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500\"><option value=\"COMMENT\">Comment</option> <option value=\"APPROVE\">Approve</option> <option value=\"REQUEST_CHANGES\">Request Changes</option></select></div><div><label class=\"block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1\" for=\"review-body\">Review body</label> <textarea id=\"review-body\" name=\"body\" x-model=\"reviewBody\" rows=\"4\" placeholder=\"Leave a comment...\" class=\"w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-y\"></textarea></div><div class=\"flex items-center gap-3\"><button type=\"submit\" class=\"px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-md transition-colors\">Submit Review</button> <span class=\"htmx-indicator text-xs text-gray-400 dark:text-gray-500\">Submitting...</span></div><div id=\"pr-review-error\" class=\"text-sm\" aria-live=\"polite\" role=\"status\" aria-atomic=\"true\"></div></form></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
